version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    networks:
      - expanse-network

networks:
  expanse-network:
    external: true
